### ISSUE TITLE
examples/basic/src/components/ToastExamples.vue

### ISSUE THREAD

**Issue by ngocvd** [paultuckey/vue3-plugin-bootstrap5#1]
https://github.com/paultuckey/vue3-plugin-bootstrap5/blob/main/examples/basic/src/components/ToastExamples.vue
Not found.

**Comment by ngocvd** [comment]
el.$vb.scrollspy = ins;

--> 
el.$vb.toast= ins;

**Comment by ngocvd** [comment]
in VbToast

**Comment by paultuckey** [comment]
Thanks for finding this.  Fixed in  v0.2.5.
